# Generated by Django 5.0.4 on 2024-05-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_flightbooking_price_alter_flightbooking_people'),
        ('payments', '0002_payment_activity_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flight_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='flights.flightbooking'),
        ),
    ]
