# Generated by Django 5.0.4 on 2024-05-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitybooking',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'BOOKED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50),
        ),
    ]
