# Generated by Django 5.0.4 on 2024-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activitybooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitybooking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitybooking',
            name='people',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
