# Generated by Django 5.0.4 on 2024-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitybooking_price_alter_activitybooking_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybooking',
            name='people',
            field=models.IntegerField(),
        ),
    ]
