# Generated by Django 5.0.4 on 2024-05-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_accomodationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodationbooking',
            name='adults',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accomodationbooking',
            name='children',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accomodationbooking',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
