# Generated by Django 5.0.4 on 2024-05-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_accomodationbooking_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationbooking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodationbooking',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
