# Generated by Django 5.0.4 on 2024-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0007_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
