# Generated by Django 5.0.4 on 2024-05-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0008_alter_accommodation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='image',
            new_name='pic',
        ),
    ]
