# Generated by Django 5.0.4 on 2024-04-29 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpath',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='flights.flight'),
            preserve_default=False,
        ),
    ]
