# Generated by Django 5.0.4 on 2024-05-08 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('flights', '0003_flightpath_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='destinations.destination')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='flights.flight')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='destinations.destination')),
            ],
        ),
        migrations.DeleteModel(
            name='FlightPath',
        ),
    ]
