# Generated by Django 5.0.4 on 2024-05-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_name_flightroute_delete_flightpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightroute',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_routes', to='flights.flight'),
        ),
        migrations.CreateModel(
            name='GeneratedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_routes', models.ManyToManyField(to='flights.flightroute')),
            ],
        ),
    ]
