# Generated by Django 5.0.4 on 2024-05-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_flightroute_flight_generatedroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedroute',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
