# Generated by Django 5.0.4 on 2024-05-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_generatedroute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedroute',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
