# Generated by Django 5.0.4 on 2024-05-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_generatedroute_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedroute',
            name='name',
        ),
    ]
