# Generated by Django 5.0.4 on 2024-04-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_end_date_booking_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
