# Generated by Django 5.0.4 on 2024-05-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_accommodation_remove_booking_activity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
